### PR TITLE
Filled in majority of CoH cards

### PR DESCRIPTION
**Pull request by clayton-grey**
This will complete the majority of the card data for CoH. I need to add the double typed mask cards, but this gets us closer.

### CODE REVIEW

**Comment by jayfehr** [comment]
The comma left at the end prevents python's json module from loading the file.

**Comment by clayton-grey** [comment]
Fixed.

**Comment by mplain** [comment]
kamalisk is not merging this because he's still working on how to implement the 2-sided masked carnevale-goers. Meanwhile I'm gonna copy-paste your mork and merge it as another pull request, minus the problematic cards.

Thanks for the help!

**Comment by clayton-grey** [comment]
That's fair. I'll stay tuned. Will ad some DWL stuff soon.

**Comment by mplain** [comment]
This can be closed now. Thanks again for your help!

**Pull request closed without merging**
