### PR TITLE
Removed double-sided from 07212a that has linked card

### PR DESCRIPTION
**Pull request by morvael**

### CODE REVIEW

**Comment by fspoettel** [comment]
This PR is a duplicate / subset of #1435

**Comment by morvael** [comment]
RTR Agenda and Act cards were missing double sided flags.

**Comment by fspoettel** [comment]
@morvael Could you please check the open PR I linked? Besides the resolution, it has these backside fixes already, alongside a few that are missing in this PR.

**Comment by morvael** [comment]
But what is the use of me checking it, I'm not the one merging the Pars anyway 😀 I just report my findings.

**Comment by drawntotheflame** [comment]
@morvael it's a fan-contributed git for arkhamdb, so if you're not willing to check, you're making work for someone else to do that checking, so as a courtesy, please do check. Thanks.

**Comment by morvael** [comment]
Sorry, if the PRs were merged faster we would never have this conflict. I'm too busy to be able to verify 27 PRs spanning 4 years. I'll refrain from proposing more fixes. After all I don't need this, due to long merge wait times I need to build workarounds around buggy data and have my mechanisms to cope with that. Good luck!

**Comment by drawntotheflame** [comment]
Thanks @morvael

**Pull request closed without merging**
