### PR TITLE
TFA weaknesses and minor fix

### PR DESCRIPTION
**Pull request by akaan**
Fixed Dr. Elli Horowitz slot and added weaknesses.

### CODE REVIEW

**Comment by Kamalisk** [comment]
the weaknesses from the campaign should be in the encounter file not in the player cards (I have not yet imported the encounter data). The new basic weakness should be here though.

**Comment by Kamalisk** [comment]
or are they all these weird new chain basicweaknesses?

**Comment by akaan** [comment]
Hi @Kamalisk !
These are indeed the chained weaknesses : the first one is a basic weakness (Dark Pact, Doomed) and the others are non-basic and are added to the player's deck by the basic ones.

**Comment by drawntotheflame** [comment]
I can have a look through all the TFA cards shortly - my pack is on the way - and make corrections. There's something odd with at least 1 mystic one I think.

**Pull request merged**
