### PR TITLE
RTPTC encounter cards, corrected

### PR DESCRIPTION
**Pull request by zzorba**

### CODE REVIEW

**Comment by zzorba** [comment]
@drawntotheflame could you review when you have a chance.

**Comment by zzorba** [comment]
One thing here -- currently the old Sickening Reality cards are technically backwards (their enemy side is the visible while their story side is marked as 'hidden').  

I had initially made the new ones with story side as the primary side (which matches how they are played), but maybe I should stick to how the old PTC cards are setup.  It certainly makes them more useful for search, since the fronts all have the same name.  LMK what you think is best.

**Comment by drawntotheflame** [comment]
I think definitely go with how OG PtC cards are setup, exactly for the reason you describe!

**Comment by zzorba** [comment]
Sounds good, went ahead and flipped them.

**Pull request merged**
