### PR TITLE
Create itm.json

### PR DESCRIPTION
**Pull request by drawntotheflame**
Adding the announced cards minus Ancestral Knowledge

### CODE REVIEW

**Comment by drawntotheflame** [comment]
No idea why the lines are formatting like that for me - or rather, why on screen they look fine and then go garbled...

**Comment by zzorba** [comment]
I believe its tabs vs spaces, seems like when Lucky Dice was copied it might have replaced them with spaces?

**Comment by akaan** [comment]
@drawntotheflame Are you using a text editor or editing it from the Github website ?
Either way, it should be correctly formatted on save thanks to Prettier.

**Comment by drawntotheflame** [comment]
@akaan I was just editing on the github website. 

@zzorba I didn't actually do any tabs *or* spaces - I just let the website align the lines... and then it seemed to change some when I saved.

**Review by robert-huang — APPROVED** [review]
lgtm!

**Pull request merged**
