### PR TITLE
 Polish translation

### PR DESCRIPTION
**Pull request by Tvaru**
Translated Guardian cards

### CODE REVIEW

**Comment by drawntotheflame** [comment]
Hey @Tvaru , it might be easier for everyone if you put the translations into a single PR rather than one per pack, given you're working through the packs by faction rather than by card? Thanks!

**Comment by Tvaru** [comment]
Hey Drawn to the flame,

Thanks for the feedback and sorry for PR spamming. I would have done it had
i known how to do it. Can you do a single PR across multiple files?

Also on a side note, do you have any relation to the drawn to the flame
podcast or is it just a cool nick you are sporting there;)?

T

W dniu wt., 13.10.2020 o 11:30 drawntotheflame <notifications@github.com>
napisał(a):

**Comment by drawntotheflame** [comment]
Hey @Tvaru 

So, the way I do it is create a PR for one file, then edit that PR, navigate to the new pack I want to edit, and make changes there. It will say 'commit directly into the same PR' and you say 'yes'. I know other arkhamdb contributors just have an entire fork of the repo that they work on, but I've not got the technical smarts to do that myself. 

By images: 

Navigate to one of your PRs and click on the branch: 

Screen Shot 2020-10-13 at 10 38 23

It shows you how ahead of the master branch it is: 

Screen Shot 2020-10-13 at 10 38 30

Navigate to the pack you want to edit, edit it, and it offers this commit option:

Screen Shot 2020-10-13 at 10 38 45

To answer your side note: I'm Frank from Drawn to the Flame! 

F

**Comment by Tvaru** [comment]
Hey Frank a.k.a. @drawntotheflame ,

Thanks for this comprehensive guide, I will try to clean up the mess that I made if it is possible and watch a few vids about GitHub before I touch anything else. Apologies for that once more to all.

I am a huge fan of your and Peter's work, thank you for it a lot :). Actually that is one of the reasons (other was ZZorba's Arkham Cards app) why I joined this initiative in the first place.

T aka T

**Comment by drawntotheflame** [comment]
Hey @Tvaru thank you - no need to apologise - it's great that you are trying to help. Appreciate the kind words about the cast; and @zzorba is here too working on arkhamdb! We're one big family! 

F

**Comment by Tvaru** [comment]
Hey @drawntotheflame Frank,

I know! Daniel aka @zzorba sent me all the data. I was not able to pull all what I did in the morning under that PR, so I closed them in a way I saw in some tutorial vid and will do them again when I have the time, under a single PR this time. Thanks again for the help, Frank

Tomasz

**Comment by drawntotheflame** [comment]
Hey @FeyrBert just tagging you in here as above you can see a very patchy guide to combine multiple PRs into a single PR, especially if you're doing lots of packs together in one go. Perhaps something to consider when you're doing lots of translations? 

(Great job @Tvaru !)

**Comment by Tvaru** [comment]
Hey @FeyrBert , that advice was golden, it saves me a lot of time not to have to create each of these separately.

@drawntotheflame Thanks again, Frank!

**Comment by FeyrBert** [comment]
@drawntotheflame 
Hey Frank!
Thanks for the tip, I'll give it a look and try to figure out something.
I wasn't sure I would end up doing as many files I did when I started, my bad :)

@Tvaru
I'll be looking into it, thanks and great job!

Bertrand

**Comment by drawntotheflame** [comment]
@Tvaru you're welcome

@FeyrBert not to worry, Bertrand, I learned the hard way too!!

**Pull request merged**
