### PR TITLE
German

### PR DESCRIPTION
**Pull request by Magnus-U**

### CODE REVIEW

**Comment by Kamalisk** [comment]
Is it normal for german to use those quotation marks? Are they like that on the official cards?

**Comment by Magnus-U** [comment]
Yes, those are the normal quotation marks in German and they are used on the official cards. An example picture is in this eBay auction: https://www.ebay.com/itm/312004160667

**Comment by mattschaffrath** [comment]
I maintain a fork that already has contributed some German translation. I seems like we're doing unnecessary double work — perhaps we should coordinate?

**Comment by Kamalisk** [comment]
Are these different translations than to the other fork? I don't want to arbitrarily pick one translation over another, so if you guys could coordinate and merge it all into one, would be helpful.

**Comment by mattschaffrath** [comment]
Yes, we were not aware that someone was working on another translation and so worked on the same files simultaneously. We'll try to coordinate.  Perhaps the easiest way would be if Magnus-U opened an issue in our fork?

**Comment by Magnus-U** [comment]
Yes, I wasn't aware of the other German fork. I think the easiest solution is that I delete my fork and fork form mattschaffrath's repository instead. Not much work would be lost since I mostly just corrected the quotation marks; the rest should be the same as mattschaffrath's translation. In the future I will open issues there when I start working on something so that we don't do double work again.

**Pull request closed without merging**
