### PR TITLE
I18N of repository

### PR DESCRIPTION
**Pull request by fafranco82**
There are two works here:

* I18N of the repository, with translations under `translations` dir. Translations to Spanish of all realeased player cards DONE.
  * Everything except cards only need `code` and `name` attributes.
  * Cards only need texts: `name`, `subname`, `text`, `flavor`, `traits`, `back_nane`, `back_text` and `back_flavor`.
  * `slot` is also translated in the files... but they will not be imported into DB by the moment.

* Added a CoffeeScript to merge new changes in default language in all locales:
  * Pre-requisites:
    * `node` and `npm` installed
    * `npm -g install coffee-script`
  * Usage: `coffee update_locales.coffee <language_code>`

### CODE REVIEW

**Comment by fafranco82** [comment]
Did you have a chance to take a look at this? If you have any doubt, don't hesitate asking me. I will love to have the site in Spanish so my non-english-speakers mates can build easily their decks :)

**Comment by Kamalisk** [comment]
I have looked at it a bit, there are a lot of changes and I haven't got much time at the moment, but will hopefully get around to it soon.

**Comment by fafranco82** [comment]
Translated all released player cards (and some encounter cards from core box)...

**Comment by Kamalisk** [comment]
I made some changes for this, will see if I can push this forward over xmas. I need to move the pack json files though as I added sub-folders for each cycle to clean up the large number of json files in one directory.

**Comment by Kamalisk** [comment]
so. more problems related to this. I basically need the english traits and text for deck validation. So I need to add further duplication to make this not break the deck builder.

**Comment by Kamalisk** [comment]
Sorry it took quite as long as this. Changes are live, need to sort out the certificate for the subdomain, but otherwise seems to work and deck building still seems fine with the changes I made. 
Thanks for the work, once this is doing ok, will see about adding files for other language requests so that people can translate if they wish.

**Comment by fafranco82** [comment]
Thanks to you for merging it!!!

Now, the next step will be translating the web interface, but that it's easy... :)

**Pull request merged**
