### PR TITLE
Start of translation into PT-BR

### PR DESCRIPTION
**Pull request by Merlynn**
We have started translating the cards into PT-BR, we are working on the translation of the ArkhamDB project and ArkhamCards. Please consider our work and add our language to the project.

### CODE REVIEW

**Comment by Merlynn** [comment]
Translation of the Core Set (player cards), cycles and some terms of what was released in PT. We are still working on the other cards.
Translation team:
Axe (eulermachado225@gmail.com)
Flash (jbmreis@gmail.com)
Kröger (denerfilho@gmail.com)

**Comment by Merlynn** [comment]
Kamalisk, are there any problems with our translation? 
Our emails are not answered, you also don't comment on our pull request

**Comment by Kamalisk** [comment]
adding support for another language requires some extra changes in addition to just the translations. I get around to stuff when I get the time. I get a lot of emails, including spam, so I often might miss things.

As for this pull request, it appears you have changed more than just the PT-BR files, so it probably needs to be rebased or fixed so it only modifies those files.

**Comment by Merlynn** [comment]
Hi, I apologize for the inconvenience, I was afraid there might be a specific reason regarding the language.

Do you think it would be better to cancel this pull request and I make a new pull request just with the changes from including PT?  I'll take advantage and add the other translations we've already done.

**Comment by Merlynn** [comment]
hi all, I submitted a new pull request with only the suggested changes. 

That's why I'm canceling this one =)

**Pull request closed without merging**
