### PR TITLE
translation to PT-BR

### PR DESCRIPTION
**Pull request by Merlynn**
hi all, I remade all the changes suggested by ZZorba and Kamalisk and I'm only sending the part relating to the translation into PT-BR

### CODE REVIEW

**Comment by Merlynn** [comment]
Hello, we have finished translating all the CORE and DWL cards. 
We will soon finish PTC.

_**Translation Team:**_
Flash (jbmreis@gmail.com)
Henrique (henricosta@gmail.com)
Kröger (denerfilho@gmail.com)
Machado (eulermachado225@gmail.com)
Mezzavilla (guga.medeiros@gmail.com)

**Comment by Merlynn** [comment]
Translated to pt-br: 
- Revised Core (Encounter and investigator)
- DWL (investigator)
- PTC (investigator)


**_Translation Team:_**
Chico (viniciuschiconato@hotmail.com)
Flash (jbmreis@gmail.com)
Henrique (henricosta@gmail.com)
Kröger (denerfilho@gmail.com)
Machado (eulermachado225@gmail.com)
Mezzavilla (guga.medeiros@gmail.com)

**Comment by Merlynn** [comment]
Translated to pt-br:

- Revised Core (Encounter and investigator)
- DWL (investigator)
- PTC (investigator)
- EOE (investigator)

**_Translation Team:_**
Chico ([viniciuschiconato@hotmail.com](mailto:viniciuschiconato@hotmail.com))
Flash ([jbmreis@gmail.com](mailto:jbmreis@gmail.com))
Henrique ([henricosta@gmail.com](mailto:henricosta@gmail.com))
Kröger ([denerfilho@gmail.com](mailto:denerfilho@gmail.com))
Machado ([eulermachado225@gmail.com](mailto:eulermachado225@gmail.com))
Mezzavilla ([guga.medeiros@gmail.com](mailto:guga.medeiros@gmail.com))

**Comment by Merlynn** [comment]
Translated to pt-br:

- Revised Core (Encounter and investigator)
- DWL (investigator)
- PTC (investigator)
- EOE (investigator)
- **TFA (investigator)**


_**Translation Team:**_
Chico ([viniciuschiconato@hotmail.com](mailto:viniciuschiconato@hotmail.com))
Flash ([jbmreis@gmail.com](mailto:jbmreis@gmail.com))
Henrique ([henricosta@gmail.com](mailto:henricosta@gmail.com))
Kröger ([denerfilho@gmail.com](mailto:denerfilho@gmail.com))
Machado ([eulermachado225@gmail.com](mailto:eulermachado225@gmail.com))
Meguer ([meguer@gmail.com](mailto:meguer@gmail.com))
Mezzavilla ([guga.medeiros@gmail.com](mailto:guga.medeiros@gmail.com))

**Comment by Kamalisk** [comment]
I need to update the cert to add the new subdomain but will see if I can do it next weekend.

**Comment by Kamalisk** [comment]
I will do my best to do it this week. sorry for not getting around to it.

**Comment by Merlynn** [comment]
> I will do my best to do it this week. sorry for not getting around to it. 

Thank you very much Kamalisk, we look forward to the update.

If you need any help, let us know and we'll try to help.

**Comment by Merlynn** [comment]
Hi, first of all, thank you very much for adding PT support.
I think it's easier to translate in the fork and send only what is necessary for your project, as this way I avoid sending some things I made to help me with the translation and I also avoid creating a branch in your project.
We have images of the cards (scanned) too, can we send them?

**Pull request merged**
