### PR TITLE
Adding parallel Rex

### PR DESCRIPTION
**Pull request by vitaemachina**

### CODE REVIEW

**Comment by zzorba** [comment]
So almost right: you need to change the dwl.json file like mine or else basic-rex won't be able to use the parallel cards.

And I THINK that you need to move a CURSED rule above the not rule, or else the exception that cursed cards are still allowed won't work.

Basically it looks through the deck rules, and if its hits a NOT it will reject the card.  But if it hits a match first, it *should* work.  Emphasis on should, there's a decent chance something gets screwy (but I think ArkhamDB will be okay with it).

**Comment by zzorba** [comment]
```
"deck_options": [
        {
          "trait": ["cursed"],
          "level": { "min": 0, "max": 4 }
        },
        {
            "not": true,
            "trait": ["fortune","blessed"],
            "level": { "min": 0, "max": 5 }
        },      
        {
          "faction": ["seeker"],
          "level": { "min": 0, "max": 3 }
        },
        {
          "faction": ["neutral"],
          "level": { "min": 0, "max": 5 }
        },
        {
          "trait": ["gambit"],
          "level": { "min": 0, "max": 4 }
        },
        {
          "faction": ["rogue"],
          "level": { "min": 0, "max": 0 },
          "limit": 5,
          "error": "You cannot have more than 5 Rogue cards."
      }
    ],
    ```

**Review by zzorba — APPROVED** [review]
This looks good

**Comment by drawntotheflame** [comment]
Thanks for contributing @vitaemachina - are you on discord? If so, @zzorba and I often liaise on there about PRs or who's adding cards so we don't double up.

**Comment by vitaemachina** [comment]
> Thanks for contributing @vitaemachina - are you on discord? If so, @zzorba and I often liaise on there about PRs or who's adding cards so we don't double up.

I am on discord generally, same username as my github username! Is there a specific server, or do you coordinate via DM?

**Comment by zzorba** [comment]
Yep, historically we have always put the 'not' rule first because they are absolute.  I believe Carolyn isn't allowed to take Runic Axe, even if it heals horror, because the Cannot/Not rule trumps the Can rule.

BUT, there is always something new and Rex has this no Blessed unless Cursed rule, hence the need to flip the order.  There is no prior art unfortunately.

**Comment by vitaemachina** [comment]
> Yep, historically we have always put the 'not' rule first because they are absolute. I believe Carolyn isn't allowed to take Runic Axe, even if it heals horror, because the Cannot/Not rule trumps the Can rule.
> 
> BUT, there is always something new and Rex has this no Blessed unless Cursed rule, hence the need to flip the order. There is no prior art unfortunately.

Awesome, good to know!

**Comment by drawntotheflame** [comment]
@vitaemachina it's the Mythos Busters server usually: https://discord.gg/mythosbusters though Zzorba and I message directly over discord too. He is zzorba, I am: zooeyglass

**Comment by Ishigh1** [comment]
There's a minor issue with this PR as is, the deckbuilding restrictions are slightly too severe, though it doesn't have any impact yet
If someday they print a level 5 neutral card that is fortune or blessed AND cursed, this current PR will say the card is invalid for Rex while it would be perfectly legal

**Comment by zzorba** [comment]
If said card comes out we can revise this then. With an extra neutral + L0-L5 rule for cursed at the start.

I will be shocked if they ever give arbitrary characters access to any L5 card.

**Comment by Ishigh1** [comment]
That would be better in my opinion to future proof it so we don't have to remember about it later, by changing how deck definitions are defined and adding a proper way to say "no fortune or blessed unless they are cursed"

**Comment by zzorba** [comment]
That's not gonna happen, certainly not for a speculative deckbuilding card that will probably never exist.

Anything that changes deck building like Versatile does will require changes to the arkhamdb code.

We can add a second rule to allow neutral + cursed level 5 cards before the not condition which covers the first condition.

**Comment by vitaemachina** [comment]
Is there anything else that I need to address with this pull request at this time? I'm not sure what the process is for getting something approved/merged, so I want to make sure nothing is being held up by me!

**Comment by drawntotheflame** [comment]
You're all good @vitaemachina ! @Kamalisk this can go live when you have a moment, thanks.

**Pull request merged**
