### PR TITLE
Added Non-Investigator Drowned City Cards

### PR DESCRIPTION
**Pull request by Renard-Chase**

### CODE REVIEW

**Comment by fspoettel** [comment]
Hello @Renard-Chase, are you aware that there is an existing PR for these cards already here #1422 ? This looks like a duplicate.

**Comment by drawntotheflame** [comment]
yep, what @fspoettel said. @Renard-Chase you can close this. If you'd like to contribute to adding cards to ArkhamDB, please search the open PRs because we have a team already working on them. Thanks!

**Comment by zzorba** [comment]
So they don't support pinning of PRs, only issues. 

I can create a milestone (TDC) and group PRs in there?

**Comment by fspoettel** [comment]
@zzorba I created a tracking issue here: https://github.com/Kamalisk/arkhamdb-json-data/issues/1453 we can pin that one

**Pull request closed without merging**
