### PR TITLE
russian translation

### PR DESCRIPTION
**Pull request by Sarnetsky**
Added Russian translation for the core set and the general files.
UPD: And all of the Dunwich.

Add/Delete difference comes from adding some flavors. Original lack thereof is addressed in #700 and #709.

### CODE REVIEW

**Comment by Sarnetsky** [comment]
@Kamalisk We've noticed that Henry Armitage (02040) is missing flavor text. Is it OK to just append the corresponding entry into the json?

**Comment by zzorba** [comment]
I opened a PR to add the missing flavor text to the english Dr. Henry Armitage. I believe you should be safe adding it to the translation file once that is merged.

**Comment by Sarnetsky** [comment]
Dunwich complete but still needs proofreading and syntax check.

**Comment by Sarnetsky** [comment]
@Kamalisk Is it okay to make PRs this big or we'd better make multiple smaller ones?

**Comment by zzorba** [comment]
I think big PRs are generally fine -- it would just be good to know when one is 'finished' and ready to be merged from your POV. 

Perhaps the right time for that would be after Forgotten Age is completed?

**Comment by Sarnetsky** [comment]
I think we'd better revert back to when dwl was done and PR from there.

**Pull request closed without merging**
