### PR TITLE
Added Ukrainian translation of Core

### PR DESCRIPTION
**Pull request by bkazydub**
Official Ukrainian translation for player and encounter cards found in core set.

### CODE REVIEW

**Comment by elkeinkrad** [comment]
The pre-defined language code for Ukranian is **uk** at [languages.css](https://github.com/Kamalisk/arkhamdb/blob/arkham/src/AppBundle/Resources/public/css/languages.css).

However, the folder name of this PR is **ua**.

I do not know whether this is critical or not, but this may cause problems.

**Comment by KazydubB** [comment]
@elkeinkrad, you are right, thank you for pointing this out! :)

@Kamalisk, is there anything else that should be done?

**Comment by bkazydub** [comment]
@elkeinkrad, you are right, thank you for pointing this out! :) Changed the directory to __uk__.

@Kamalisk, is there anything else that should be done?

**Comment by Kamalisk** [comment]
I need to the add the subdomain and set up the certificate before it can be live, but translating the files is you need to handle :P

**Pull request merged**
