### PR TITLE
Add Chinese cards of side/guardian. Unify translations of "when...", "at..." and  "while..."

### PR DESCRIPTION
**Pull request by shkuo**

### CODE REVIEW

**Comment by shkuo** [comment]
Hello Kamalisk, 
I am doing Chinese translations. Mostly I key-in those existing Chinese cards. 
For those packs that don't have Chinese version yet, sometimes I translate them by myself, follow the rules of existing translations.
May I ask a question?
The previous pull-requests were accepted, and were updated on Github.
But it is not updated on the website? Is anything wrong with the translation files?

My fellow translation volunteers are a little bit eager to see their results, especially the newly released Chinese tcu packs.
Thanks a lot.

Best Regards,
SH

**Comment by Kamalisk** [comment]
They should be updated, I will double check, its possible I forgot to run the import after translating.

**Comment by Kamalisk** [comment]
@shkuo I found an error in the blob file and fixed it, so should all be updated now.

**Comment by Kamalisk** [comment]
also if you guys want to translate some of the UI text to chinese, you can do so here
https://github.com/Kamalisk/arkhamdb/blob/arkham/src/AppBundle/Resources/translations/messages.zh.xlf

**Pull request merged**
