### PR TITLE
Update player card translations german

### PR DESCRIPTION
**Pull request by tjanu**
If this is merged, only the translations of the new cards from the investigator starter decks are missing.

Parallel Skids sadly did not get a german release yet.

### CODE REVIEW

**Comment by chrizzH** [comment]
Hey, are you working on the investigator decks?
Im into it, but you are a lot faster than me. So i would push what i did and you can continue.

**Comment by tjanu** [comment]
@chrizzH I would start those next. Apparently, Jaqueline Fine was done while I was working on innsmouth, and I won't have any time today and on Thursday. Maybe we can split them up? I own all of them, so you can pick and choose of you want to.

**Comment by chrizzH** [comment]
Ok, so maybe you can do a branch in your fork for this translation, or i give you access to mine.

**Comment by tjanu** [comment]
@chrizzH I invited you as a collaborator on my fork and created an update_investigator_decks branch

**Comment by huberchrigu** [comment]
@tjanu Haven't seen your PR, so I already translated the player cards of TCU. I also fixed some typos of existing translations. Do you want to diff with [my commit](https://github.com/Kamalisk/arkhamdb-json-data/pull/798/commits/2a1e487fe381d272454c466bce8476beed4faf51)? Then I'll close my PR.

**Comment by tjanu** [comment]
@huberchrigu I'll review the diff when I get home from work

**Comment by Kamalisk** [comment]
you appeared to have changed other translations than german?

**Comment by tjanu** [comment]
I once ran update_locales.coffee without an argument by mistake, so I just created the missing placeholders for all languages. Should I try to create a new branch without that commit or can you deal with those 2 files that conflict now on merge?

**Comment by tjanu** [comment]
I reverted the erroneously argumentless execution of update_locales.coffee - touching of other translations is now undone, except for a very little conflict in the spanisch pack listing, which is also resolved.

**Comment by tjanu** [comment]
@Kamalisk I cleaned up the messed up update_locales.coffee execution, finally. Now only German translations are touched by this PR, and together with my new PR #829, this would translate all the player cards as far as they are currently released.

**Comment by Kamalisk** [comment]
thanks

**Pull request merged**
